#  Add your deisred hosts to the inventory
#  Specify the username, ssh port and IP address
---
all:
  hosts:
    raspberry_pi:
      ansible_user: pi
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_host: 192.168.1.15 
  vars:
    ansible_port: 22

    