#  A simple ansible playbook for setting up a new server
#  Author: Szymon Hankus
---
- name: A basic setup
  hosts: all
  tasks:
    - name: "Add a new user - {{ username }}"
      become: true
      ansible.builtin.user:
        state: present
        name: "{{ username }}"
        shell: /bin/bash
        create_home: true
        password: "{{ 'abc' | password_hash('sha512', 'mysecretsalt') }}"
        update_password: always

    - name: "Add the new user to /etc/sudoers ({{ username }})"
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        state: present
        line: "{{ username }} ALL=(ALL:ALL) ALL"
        validate: "visudo -cf %s"

    - name: Add an authorized SSH public key
      become: true
      ansible.posix.authorized_key:
        state: present
        user: "{{ username }}"
        key: "{{ lookup('file', ssh_public_key_path) }}"  # path defined in group_vars

    - name: Configure SSHD
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication no"}
        - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no"}
        - { regexp: "^#?Port", line: "Port {{ ssh_port }}"}

    - name: Restart the SSHD service
      become: true
      ansible.builtin.systemd:
        state: reloaded
        name: sshd

    - name: Install necessary packages
      become: true
      ansible.builtin.package:
        name:
          - git
          - stow
          - acl  # used for becoming an unpriviledged user (https://github.com/georchestra/ansible/issues/55#issuecomment-588313638)
          - vim
          - ranger
        state: present

    - name: Clone a 'dotfiles' repository
      become: true
      become_user: "{{ username }}"
      ansible.builtin.git:
        repo: "{{ dotfiles_repo }}"
        dest: "/home/{{ username }}/dotfiles"
        recursive: false
        force: true
