username: szymon
password: "{{ vault_password }}"
ssh_port: 43210
ssh_public_key_path: ~/.ssh/id_ed25519.pub

dotfiles_repo: https://github.com/sz-hankus/dotfiles.git
packages: 
  - git
  - stow
  - acl  # used for becoming an unpriviledged user (https://github.com/georchestra/ansible/issues/55#issuecomment-588313638)
  - vim
  - neovim
  - fish
  - ranger
