# Setup my personal work environment
---
- name: Install necessary packages
  become: true
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Clone a 'dotfiles' repository
  become: true
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/dotfiles"
    recursive: false
    force: true
