# Setup up SSHD options and reload the service (if changes were made)
---
- name: Configure SSHD
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication no"}
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no"}
    - { regexp: "^#?Port", line: "Port {{ ssh_port }}"}
  register: sshd_status

- name: Reload the SSHD service (when sshd_config changed)
  become: true
  when: sshd_status.changed
  ansible.builtin.systemd:
    state: reloaded
    name: sshd
